// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Counter(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* count */state[/* count */0] + 1 | 0];
        }), /* record */[/* count */0]);
  var dispatch = match[1];
  var message = "You've clicked this " + (String(match[0][/* count */0]) + " times(s)");
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Click */0);
                    })
                }, message));
}

var make = Counter;

exports.make = make;
/* react Not a pure module */
