// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var countries = /* array */[
  /* record */[
    /* timezones : :: */[
      "America/Aruba",
      /* [] */0
    ],
    /* latlng : tuple */[
      12.5,
      -69.96666666
    ],
    /* name */"Aruba",
    /* country_code */"AW",
    /* capital */"Oranjestad"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Kabul",
      /* [] */0
    ],
    /* latlng : tuple */[
      33,
      65
    ],
    /* name */"Afghanistan",
    /* country_code */"AF",
    /* capital */"Kabul"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Luanda",
      /* [] */0
    ],
    /* latlng : tuple */[
      -12.5,
      18.5
    ],
    /* name */"Angola",
    /* country_code */"AO",
    /* capital */"Luanda"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Anguilla",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.25,
      -63.16666666
    ],
    /* name */"Anguilla",
    /* country_code */"AI",
    /* capital */"The Valley"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Mariehamn",
      /* [] */0
    ],
    /* latlng : tuple */[
      60.116667,
      19.9
    ],
    /* name */"Aland Islands",
    /* country_code */"AX",
    /* capital */"Mariehamn"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Tirane",
      /* [] */0
    ],
    /* latlng : tuple */[
      41,
      20
    ],
    /* name */"Albania",
    /* country_code */"AL",
    /* capital */"Tirana"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Andorra",
      /* [] */0
    ],
    /* latlng : tuple */[
      42.5,
      1.5
    ],
    /* name */"Andorra",
    /* country_code */"AD",
    /* capital */"Andorra la Vella"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Dubai",
      /* [] */0
    ],
    /* latlng : tuple */[
      24,
      54
    ],
    /* name */"United Arab Emirates",
    /* country_code */"AE",
    /* capital */"Abu Dhabi"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Argentina/Buenos_Aires",
      /* :: */[
        "America/Argentina/Cordoba",
        /* :: */[
          "America/Argentina/Salta",
          /* :: */[
            "America/Argentina/Jujuy",
            /* :: */[
              "America/Argentina/Tucuman",
              /* :: */[
                "America/Argentina/Catamarca",
                /* :: */[
                  "America/Argentina/La_Rioja",
                  /* :: */[
                    "America/Argentina/San_Juan",
                    /* :: */[
                      "America/Argentina/Mendoza",
                      /* :: */[
                        "America/Argentina/San_Luis",
                        /* :: */[
                          "America/Argentina/Rio_Gallegos",
                          /* :: */[
                            "America/Argentina/Ushuaia",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      -34,
      -64
    ],
    /* name */"Argentina",
    /* country_code */"AR",
    /* capital */"Buenos Aires"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Yerevan",
      /* [] */0
    ],
    /* latlng : tuple */[
      40,
      45
    ],
    /* name */"Armenia",
    /* country_code */"AM",
    /* capital */"Yerevan"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Pago_Pago",
      /* [] */0
    ],
    /* latlng : tuple */[
      -14.33333333,
      -170
    ],
    /* name */"American Samoa",
    /* country_code */"AS",
    /* capital */"Pago Pago"
  ],
  /* record */[
    /* timezones : :: */[
      "Antarctica/McMurdo",
      /* :: */[
        "Antarctica/Casey",
        /* :: */[
          "Antarctica/Davis",
          /* :: */[
            "Antarctica/DumontDUrville",
            /* :: */[
              "Antarctica/Mawson",
              /* :: */[
                "Antarctica/Palmer",
                /* :: */[
                  "Antarctica/Rothera",
                  /* :: */[
                    "Antarctica/Syowa",
                    /* :: */[
                      "Antarctica/Troll",
                      /* :: */[
                        "Antarctica/Vostok",
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      -90,
      0
    ],
    /* name */"Antarctica",
    /* country_code */"AQ",
    /* capital */"Antarctica"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Kerguelen",
      /* [] */0
    ],
    /* latlng : tuple */[
      -49.25,
      69.167
    ],
    /* name */"French Southern and Antarctic Lands",
    /* country_code */"TF",
    /* capital */"Port-aux-Fran\\u00e7ais"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Antigua",
      /* [] */0
    ],
    /* latlng : tuple */[
      17.05,
      -61.8
    ],
    /* name */"Antigua and Barbuda",
    /* country_code */"AG",
    /* capital */"Saint John's"
  ],
  /* record */[
    /* timezones : :: */[
      "Australia/Lord_Howe",
      /* :: */[
        "Antarctica/Macquarie",
        /* :: */[
          "Australia/Hobart",
          /* :: */[
            "Australia/Currie",
            /* :: */[
              "Australia/Melbourne",
              /* :: */[
                "Australia/Sydney",
                /* :: */[
                  "Australia/Broken_Hill",
                  /* :: */[
                    "Australia/Brisbane",
                    /* :: */[
                      "Australia/Lindeman",
                      /* :: */[
                        "Australia/Adelaide",
                        /* :: */[
                          "Australia/Darwin",
                          /* :: */[
                            "Australia/Perth",
                            /* :: */[
                              "Australia/Eucla",
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      -27,
      133
    ],
    /* name */"Australia",
    /* country_code */"AU",
    /* capital */"Canberra"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Vienna",
      /* [] */0
    ],
    /* latlng : tuple */[
      47.33333333,
      13.33333333
    ],
    /* name */"Austria",
    /* country_code */"AT",
    /* capital */"Vienna"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Baku",
      /* [] */0
    ],
    /* latlng : tuple */[
      40.5,
      47.5
    ],
    /* name */"Azerbaijan",
    /* country_code */"AZ",
    /* capital */"Baku"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Bujumbura",
      /* [] */0
    ],
    /* latlng : tuple */[
      -3.5,
      30
    ],
    /* name */"Burundi",
    /* country_code */"BI",
    /* capital */"Bujumbura"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Brussels",
      /* [] */0
    ],
    /* latlng : tuple */[
      50.83333333,
      4
    ],
    /* name */"Belgium",
    /* country_code */"BE",
    /* capital */"Brussels"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Porto-Novo",
      /* [] */0
    ],
    /* latlng : tuple */[
      9.5,
      2.25
    ],
    /* name */"Benin",
    /* country_code */"BJ",
    /* capital */"Porto-Novo"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Ouagadougou",
      /* [] */0
    ],
    /* latlng : tuple */[
      13,
      -2
    ],
    /* name */"Burkina Faso",
    /* country_code */"BF",
    /* capital */"Ouagadougou"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Dhaka",
      /* [] */0
    ],
    /* latlng : tuple */[
      24,
      90
    ],
    /* name */"Bangladesh",
    /* country_code */"BD",
    /* capital */"Dhaka"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Sofia",
      /* [] */0
    ],
    /* latlng : tuple */[
      43,
      25
    ],
    /* name */"Bulgaria",
    /* country_code */"BG",
    /* capital */"Sofia"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Bahrain",
      /* [] */0
    ],
    /* latlng : tuple */[
      26,
      50.55
    ],
    /* name */"Bahrain",
    /* country_code */"BH",
    /* capital */"Manama"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Nassau",
      /* [] */0
    ],
    /* latlng : tuple */[
      24.25,
      -76
    ],
    /* name */"Bahamas",
    /* country_code */"BS",
    /* capital */"Nassau"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Sarajevo",
      /* [] */0
    ],
    /* latlng : tuple */[
      44,
      18
    ],
    /* name */"Bosnia and Herzegovina",
    /* country_code */"BA",
    /* capital */"Sarajevo"
  ],
  /* record */[
    /* timezones : :: */[
      "America/St_Barthelemy",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.5,
      -63.41666666
    ],
    /* name */"Saint Barth\\u00e9lemy",
    /* country_code */"BL",
    /* capital */"Gustavia"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Minsk",
      /* [] */0
    ],
    /* latlng : tuple */[
      53,
      28
    ],
    /* name */"Belarus",
    /* country_code */"BY",
    /* capital */"Minsk"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Belize",
      /* [] */0
    ],
    /* latlng : tuple */[
      17.25,
      -88.75
    ],
    /* name */"Belize",
    /* country_code */"BZ",
    /* capital */"Belmopan"
  ],
  /* record */[
    /* timezones : :: */[
      "Atlantic/Bermuda",
      /* [] */0
    ],
    /* latlng : tuple */[
      32.33333333,
      -64.75
    ],
    /* name */"Bermuda",
    /* country_code */"BM",
    /* capital */"Hamilton"
  ],
  /* record */[
    /* timezones : :: */[
      "America/La_Paz",
      /* [] */0
    ],
    /* latlng : tuple */[
      -17,
      -65
    ],
    /* name */"Bolivia",
    /* country_code */"BO",
    /* capital */"Sucre"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Noronha",
      /* :: */[
        "America/Belem",
        /* :: */[
          "America/Fortaleza",
          /* :: */[
            "America/Recife",
            /* :: */[
              "America/Araguaina",
              /* :: */[
                "America/Maceio",
                /* :: */[
                  "America/Bahia",
                  /* :: */[
                    "America/Sao_Paulo",
                    /* :: */[
                      "America/Campo_Grande",
                      /* :: */[
                        "America/Cuiaba",
                        /* :: */[
                          "America/Santarem",
                          /* :: */[
                            "America/Porto_Velho",
                            /* :: */[
                              "America/Boa_Vista",
                              /* :: */[
                                "America/Manaus",
                                /* :: */[
                                  "America/Eirunepe",
                                  /* :: */[
                                    "America/Rio_Branco",
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      -10,
      -55
    ],
    /* name */"Brazil",
    /* country_code */"BR",
    /* capital */"Bras\\u00edlia"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Barbados",
      /* [] */0
    ],
    /* latlng : tuple */[
      13.16666666,
      -59.53333333
    ],
    /* name */"Barbados",
    /* country_code */"BB",
    /* capital */"Bridgetown"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Brunei",
      /* [] */0
    ],
    /* latlng : tuple */[
      4.5,
      114.66666666
    ],
    /* name */"Brunei",
    /* country_code */"BN",
    /* capital */"Bandar Seri Begawan"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Thimphu",
      /* [] */0
    ],
    /* latlng : tuple */[
      27.5,
      90.5
    ],
    /* name */"Bhutan",
    /* country_code */"BT",
    /* capital */"Thimphu"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Oslo",
      /* [] */0
    ],
    /* latlng : tuple */[
      -54.43333333,
      3.4
    ],
    /* name */"Bouvet Island",
    /* country_code */"BV",
    /* capital */"Bouvet Island"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Gaborone",
      /* [] */0
    ],
    /* latlng : tuple */[
      -22,
      24
    ],
    /* name */"Botswana",
    /* country_code */"BW",
    /* capital */"Gaborone"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Bangui",
      /* [] */0
    ],
    /* latlng : tuple */[
      7,
      21
    ],
    /* name */"Central African Republic",
    /* country_code */"CF",
    /* capital */"Bangui"
  ],
  /* record */[
    /* timezones : :: */[
      "America/St_Johns",
      /* :: */[
        "America/Halifax",
        /* :: */[
          "America/Glace_Bay",
          /* :: */[
            "America/Moncton",
            /* :: */[
              "America/Goose_Bay",
              /* :: */[
                "America/Blanc-Sablon",
                /* :: */[
                  "America/Toronto",
                  /* :: */[
                    "America/Nipigon",
                    /* :: */[
                      "America/Thunder_Bay",
                      /* :: */[
                        "America/Iqaluit",
                        /* :: */[
                          "America/Pangnirtung",
                          /* :: */[
                            "America/Atikokan",
                            /* :: */[
                              "America/Winnipeg",
                              /* :: */[
                                "America/Rainy_River",
                                /* :: */[
                                  "America/Resolute",
                                  /* :: */[
                                    "America/Rankin_Inlet",
                                    /* :: */[
                                      "America/Regina",
                                      /* :: */[
                                        "America/Swift_Current",
                                        /* :: */[
                                          "America/Edmonton",
                                          /* :: */[
                                            "America/Cambridge_Bay",
                                            /* :: */[
                                              "America/Yellowknife",
                                              /* :: */[
                                                "America/Inuvik",
                                                /* :: */[
                                                  "America/Creston",
                                                  /* :: */[
                                                    "America/Dawson_Creek",
                                                    /* :: */[
                                                      "America/Fort_Nelson",
                                                      /* :: */[
                                                        "America/Vancouver",
                                                        /* :: */[
                                                          "America/Whitehorse",
                                                          /* :: */[
                                                            "America/Dawson",
                                                            /* [] */0
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      60,
      -95
    ],
    /* name */"Canada",
    /* country_code */"CA",
    /* capital */"Ottawa"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Cocos",
      /* [] */0
    ],
    /* latlng : tuple */[
      -12.5,
      96.83333333
    ],
    /* name */"Cocos (Keeling) Islands",
    /* country_code */"CC",
    /* capital */"West Island"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Zurich",
      /* [] */0
    ],
    /* latlng : tuple */[
      47,
      8
    ],
    /* name */"Switzerland",
    /* country_code */"CH",
    /* capital */"Bern"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Santiago",
      /* :: */[
        "Pacific/Easter",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      -30,
      -71
    ],
    /* name */"Chile",
    /* country_code */"CL",
    /* capital */"Santiago"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Shanghai",
      /* :: */[
        "Asia/Urumqi",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      35,
      105
    ],
    /* name */"China",
    /* country_code */"CN",
    /* capital */"Beijing"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Abidjan",
      /* [] */0
    ],
    /* latlng : tuple */[
      8,
      -5
    ],
    /* name */"Ivory Coast",
    /* country_code */"CI",
    /* capital */"Yamoussoukro"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Douala",
      /* [] */0
    ],
    /* latlng : tuple */[
      6,
      12
    ],
    /* name */"Cameroon",
    /* country_code */"CM",
    /* capital */"Yaound\\u00e9"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Kinshasa",
      /* :: */[
        "Africa/Lubumbashi",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      0,
      25
    ],
    /* name */"DR Congo",
    /* country_code */"CD",
    /* capital */"Kinshasa"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Brazzaville",
      /* [] */0
    ],
    /* latlng : tuple */[
      -1,
      15
    ],
    /* name */"Republic of the Congo",
    /* country_code */"CG",
    /* capital */"Brazzaville"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Rarotonga",
      /* [] */0
    ],
    /* latlng : tuple */[
      -21.23333333,
      -159.76666666
    ],
    /* name */"Cook Islands",
    /* country_code */"CK",
    /* capital */"Avarua"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Bogota",
      /* [] */0
    ],
    /* latlng : tuple */[
      4,
      -72
    ],
    /* name */"Colombia",
    /* country_code */"CO",
    /* capital */"Bogot\\u00e1"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Comoro",
      /* [] */0
    ],
    /* latlng : tuple */[
      -12.16666666,
      44.25
    ],
    /* name */"Comoros",
    /* country_code */"KM",
    /* capital */"Moroni"
  ],
  /* record */[
    /* timezones : :: */[
      "Atlantic/Cape_Verde",
      /* [] */0
    ],
    /* latlng : tuple */[
      16,
      -24
    ],
    /* name */"Cape Verde",
    /* country_code */"CV",
    /* capital */"Praia"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Costa_Rica",
      /* [] */0
    ],
    /* latlng : tuple */[
      10,
      -84
    ],
    /* name */"Costa Rica",
    /* country_code */"CR",
    /* capital */"San Jos\\u00e9"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Havana",
      /* [] */0
    ],
    /* latlng : tuple */[
      21.5,
      -80
    ],
    /* name */"Cuba",
    /* country_code */"CU",
    /* capital */"Havana"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Curacao",
      /* [] */0
    ],
    /* latlng : tuple */[
      12.116667,
      -68.933333
    ],
    /* name */"Cura\\u00e7ao",
    /* country_code */"CW",
    /* capital */"Willemstad"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Christmas",
      /* [] */0
    ],
    /* latlng : tuple */[
      -10.5,
      105.66666666
    ],
    /* name */"Christmas Island",
    /* country_code */"CX",
    /* capital */"Flying Fish Cove"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Cayman",
      /* [] */0
    ],
    /* latlng : tuple */[
      19.5,
      -80.5
    ],
    /* name */"Cayman Islands",
    /* country_code */"KY",
    /* capital */"George Town"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Nicosia",
      /* [] */0
    ],
    /* latlng : tuple */[
      35,
      33
    ],
    /* name */"Cyprus",
    /* country_code */"CY",
    /* capital */"Nicosia"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Prague",
      /* [] */0
    ],
    /* latlng : tuple */[
      49.75,
      15.5
    ],
    /* name */"Czech Republic",
    /* country_code */"CZ",
    /* capital */"Prague"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Berlin",
      /* :: */[
        "Europe/Busingen",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      51,
      9
    ],
    /* name */"Germany",
    /* country_code */"DE",
    /* capital */"Berlin"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Djibouti",
      /* [] */0
    ],
    /* latlng : tuple */[
      11.5,
      43
    ],
    /* name */"Djibouti",
    /* country_code */"DJ",
    /* capital */"Djibouti"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Dominica",
      /* [] */0
    ],
    /* latlng : tuple */[
      15.41666666,
      -61.33333333
    ],
    /* name */"Dominica",
    /* country_code */"DM",
    /* capital */"Roseau"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Copenhagen",
      /* [] */0
    ],
    /* latlng : tuple */[
      56,
      10
    ],
    /* name */"Denmark",
    /* country_code */"DK",
    /* capital */"Copenhagen"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Santo_Domingo",
      /* [] */0
    ],
    /* latlng : tuple */[
      19,
      -70.66666666
    ],
    /* name */"Dominican Republic",
    /* country_code */"DO",
    /* capital */"Santo Domingo"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Algiers",
      /* [] */0
    ],
    /* latlng : tuple */[
      28,
      3
    ],
    /* name */"Algeria",
    /* country_code */"DZ",
    /* capital */"Algiers"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Guayaquil",
      /* :: */[
        "Pacific/Galapagos",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      -2,
      -77.5
    ],
    /* name */"Ecuador",
    /* country_code */"EC",
    /* capital */"Quito"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Cairo",
      /* [] */0
    ],
    /* latlng : tuple */[
      27,
      30
    ],
    /* name */"Egypt",
    /* country_code */"EG",
    /* capital */"Cairo"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Asmara",
      /* [] */0
    ],
    /* latlng : tuple */[
      15,
      39
    ],
    /* name */"Eritrea",
    /* country_code */"ER",
    /* capital */"Asmara"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/El_Aaiun",
      /* [] */0
    ],
    /* latlng : tuple */[
      24.5,
      -13
    ],
    /* name */"Western Sahara",
    /* country_code */"EH",
    /* capital */"El Aai\\u00fan"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Madrid",
      /* :: */[
        "Africa/Ceuta",
        /* :: */[
          "Atlantic/Canary",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      40,
      -4
    ],
    /* name */"Spain",
    /* country_code */"ES",
    /* capital */"Madrid"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Tallinn",
      /* [] */0
    ],
    /* latlng : tuple */[
      59,
      26
    ],
    /* name */"Estonia",
    /* country_code */"EE",
    /* capital */"Tallinn"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Addis_Ababa",
      /* [] */0
    ],
    /* latlng : tuple */[
      8,
      38
    ],
    /* name */"Ethiopia",
    /* country_code */"ET",
    /* capital */"Addis Ababa"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Helsinki",
      /* [] */0
    ],
    /* latlng : tuple */[
      64,
      26
    ],
    /* name */"Finland",
    /* country_code */"FI",
    /* capital */"Helsinki"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Fiji",
      /* [] */0
    ],
    /* latlng : tuple */[
      -18,
      175
    ],
    /* name */"Fiji",
    /* country_code */"FJ",
    /* capital */"Suva"
  ],
  /* record */[
    /* timezones : :: */[
      "Atlantic/Stanley",
      /* [] */0
    ],
    /* latlng : tuple */[
      -51.75,
      -59
    ],
    /* name */"Falkland Islands",
    /* country_code */"FK",
    /* capital */"Stanley"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Paris",
      /* [] */0
    ],
    /* latlng : tuple */[
      46,
      2
    ],
    /* name */"France",
    /* country_code */"FR",
    /* capital */"Paris"
  ],
  /* record */[
    /* timezones : :: */[
      "Atlantic/Faroe",
      /* [] */0
    ],
    /* latlng : tuple */[
      62,
      -7
    ],
    /* name */"Faroe Islands",
    /* country_code */"FO",
    /* capital */"T\\u00f3rshavn"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Chuuk",
      /* :: */[
        "Pacific/Pohnpei",
        /* :: */[
          "Pacific/Kosrae",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      6.91666666,
      158.25
    ],
    /* name */"Micronesia",
    /* country_code */"FM",
    /* capital */"Palikir"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Libreville",
      /* [] */0
    ],
    /* latlng : tuple */[
      -1,
      11.75
    ],
    /* name */"Gabon",
    /* country_code */"GA",
    /* capital */"Libreville"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/London",
      /* [] */0
    ],
    /* latlng : tuple */[
      54,
      -2
    ],
    /* name */"United Kingdom",
    /* country_code */"GB",
    /* capital */"London"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Tbilisi",
      /* [] */0
    ],
    /* latlng : tuple */[
      42,
      43.5
    ],
    /* name */"Georgia",
    /* country_code */"GE",
    /* capital */"Tbilisi"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Guernsey",
      /* [] */0
    ],
    /* latlng : tuple */[
      49.46666666,
      -2.58333333
    ],
    /* name */"Guernsey",
    /* country_code */"GG",
    /* capital */"St. Peter Port"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Accra",
      /* [] */0
    ],
    /* latlng : tuple */[
      8,
      -2
    ],
    /* name */"Ghana",
    /* country_code */"GH",
    /* capital */"Accra"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Gibraltar",
      /* [] */0
    ],
    /* latlng : tuple */[
      36.13333333,
      -5.35
    ],
    /* name */"Gibraltar",
    /* country_code */"GI",
    /* capital */"Gibraltar"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Conakry",
      /* [] */0
    ],
    /* latlng : tuple */[
      11,
      -10
    ],
    /* name */"Guinea",
    /* country_code */"GN",
    /* capital */"Conakry"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Guadeloupe",
      /* [] */0
    ],
    /* latlng : tuple */[
      16.25,
      -61.583333
    ],
    /* name */"Guadeloupe",
    /* country_code */"GP",
    /* capital */"Basse-Terre"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Banjul",
      /* [] */0
    ],
    /* latlng : tuple */[
      13.46666666,
      -16.56666666
    ],
    /* name */"Gambia",
    /* country_code */"GM",
    /* capital */"Banjul"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Bissau",
      /* [] */0
    ],
    /* latlng : tuple */[
      12,
      -15
    ],
    /* name */"Guinea-Bissau",
    /* country_code */"GW",
    /* capital */"Bissau"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Malabo",
      /* [] */0
    ],
    /* latlng : tuple */[
      2,
      10
    ],
    /* name */"Equatorial Guinea",
    /* country_code */"GQ",
    /* capital */"Malabo"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Athens",
      /* [] */0
    ],
    /* latlng : tuple */[
      39,
      22
    ],
    /* name */"Greece",
    /* country_code */"GR",
    /* capital */"Athens"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Grenada",
      /* [] */0
    ],
    /* latlng : tuple */[
      12.11666666,
      -61.66666666
    ],
    /* name */"Grenada",
    /* country_code */"GD",
    /* capital */"St. George's"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Godthab",
      /* :: */[
        "America/Danmarkshavn",
        /* :: */[
          "America/Scoresbysund",
          /* :: */[
            "America/Thule",
            /* [] */0
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      72,
      -40
    ],
    /* name */"Greenland",
    /* country_code */"GL",
    /* capital */"Nuuk"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Guatemala",
      /* [] */0
    ],
    /* latlng : tuple */[
      15.5,
      -90.25
    ],
    /* name */"Guatemala",
    /* country_code */"GT",
    /* capital */"Guatemala City"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Cayenne",
      /* [] */0
    ],
    /* latlng : tuple */[
      4,
      -53
    ],
    /* name */"French Guiana",
    /* country_code */"GF",
    /* capital */"Cayenne"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Guam",
      /* [] */0
    ],
    /* latlng : tuple */[
      13.46666666,
      144.78333333
    ],
    /* name */"Guam",
    /* country_code */"GU",
    /* capital */"Hag\\u00e5t\\u00f1a"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Guyana",
      /* [] */0
    ],
    /* latlng : tuple */[
      5,
      -59
    ],
    /* name */"Guyana",
    /* country_code */"GY",
    /* capital */"Georgetown"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Hong_Kong",
      /* [] */0
    ],
    /* latlng : tuple */[
      22.267,
      114.188
    ],
    /* name */"Hong Kong",
    /* country_code */"HK",
    /* capital */"City of Victoria"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Tegucigalpa",
      /* [] */0
    ],
    /* latlng : tuple */[
      15,
      -86.5
    ],
    /* name */"Honduras",
    /* country_code */"HN",
    /* capital */"Tegucigalpa"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Zagreb",
      /* [] */0
    ],
    /* latlng : tuple */[
      45.16666666,
      15.5
    ],
    /* name */"Croatia",
    /* country_code */"HR",
    /* capital */"Zagreb"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Port-au-Prince",
      /* [] */0
    ],
    /* latlng : tuple */[
      19,
      -72.41666666
    ],
    /* name */"Haiti",
    /* country_code */"HT",
    /* capital */"Port-au-Prince"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Budapest",
      /* [] */0
    ],
    /* latlng : tuple */[
      47,
      20
    ],
    /* name */"Hungary",
    /* country_code */"HU",
    /* capital */"Budapest"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Jakarta",
      /* :: */[
        "Asia/Pontianak",
        /* :: */[
          "Asia/Makassar",
          /* :: */[
            "Asia/Jayapura",
            /* [] */0
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      -5,
      120
    ],
    /* name */"Indonesia",
    /* country_code */"ID",
    /* capital */"Jakarta"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Isle_of_Man",
      /* [] */0
    ],
    /* latlng : tuple */[
      54.25,
      -4.5
    ],
    /* name */"Isle of Man",
    /* country_code */"IM",
    /* capital */"Douglas"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Kolkata",
      /* [] */0
    ],
    /* latlng : tuple */[
      20,
      77
    ],
    /* name */"India",
    /* country_code */"IN",
    /* capital */"New Delhi"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Chagos",
      /* [] */0
    ],
    /* latlng : tuple */[
      -6,
      71.5
    ],
    /* name */"British Indian Ocean Territory",
    /* country_code */"IO",
    /* capital */"Diego Garcia"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Dublin",
      /* [] */0
    ],
    /* latlng : tuple */[
      53,
      -8
    ],
    /* name */"Ireland",
    /* country_code */"IE",
    /* capital */"Dublin"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Tehran",
      /* [] */0
    ],
    /* latlng : tuple */[
      32,
      53
    ],
    /* name */"Iran",
    /* country_code */"IR",
    /* capital */"Tehran"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Baghdad",
      /* [] */0
    ],
    /* latlng : tuple */[
      33,
      44
    ],
    /* name */"Iraq",
    /* country_code */"IQ",
    /* capital */"Baghdad"
  ],
  /* record */[
    /* timezones : :: */[
      "Atlantic/Reykjavik",
      /* [] */0
    ],
    /* latlng : tuple */[
      65,
      -18
    ],
    /* name */"Iceland",
    /* country_code */"IS",
    /* capital */"Reykjavik"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Jerusalem",
      /* [] */0
    ],
    /* latlng : tuple */[
      31.47,
      35.13
    ],
    /* name */"Israel",
    /* country_code */"IL",
    /* capital */"Jerusalem"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Rome",
      /* [] */0
    ],
    /* latlng : tuple */[
      42.83333333,
      12.83333333
    ],
    /* name */"Italy",
    /* country_code */"IT",
    /* capital */"Rome"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Jamaica",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.25,
      -77.5
    ],
    /* name */"Jamaica",
    /* country_code */"JM",
    /* capital */"Kingston"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Jersey",
      /* [] */0
    ],
    /* latlng : tuple */[
      49.25,
      -2.16666666
    ],
    /* name */"Jersey",
    /* country_code */"JE",
    /* capital */"Saint Helier"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Amman",
      /* [] */0
    ],
    /* latlng : tuple */[
      31,
      36
    ],
    /* name */"Jordan",
    /* country_code */"JO",
    /* capital */"Amman"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Tokyo",
      /* [] */0
    ],
    /* latlng : tuple */[
      36,
      138
    ],
    /* name */"Japan",
    /* country_code */"JP",
    /* capital */"Tokyo"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Almaty",
      /* :: */[
        "Asia/Qyzylorda",
        /* :: */[
          "Asia/Aqtobe",
          /* :: */[
            "Asia/Aqtau",
            /* :: */[
              "Asia/Oral",
              /* [] */0
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      48,
      68
    ],
    /* name */"Kazakhstan",
    /* country_code */"KZ",
    /* capital */"Astana"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Nairobi",
      /* [] */0
    ],
    /* latlng : tuple */[
      1,
      38
    ],
    /* name */"Kenya",
    /* country_code */"KE",
    /* capital */"Nairobi"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Bishkek",
      /* [] */0
    ],
    /* latlng : tuple */[
      41,
      75
    ],
    /* name */"Kyrgyzstan",
    /* country_code */"KG",
    /* capital */"Bishkek"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Phnom_Penh",
      /* [] */0
    ],
    /* latlng : tuple */[
      13,
      105
    ],
    /* name */"Cambodia",
    /* country_code */"KH",
    /* capital */"Phnom Penh"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Tarawa",
      /* :: */[
        "Pacific/Enderbury",
        /* :: */[
          "Pacific/Kiritimati",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      1.41666666,
      173
    ],
    /* name */"Kiribati",
    /* country_code */"KI",
    /* capital */"South Tarawa"
  ],
  /* record */[
    /* timezones : :: */[
      "America/St_Kitts",
      /* [] */0
    ],
    /* latlng : tuple */[
      17.33333333,
      -62.75
    ],
    /* name */"Saint Kitts and Nevis",
    /* country_code */"KN",
    /* capital */"Basseterre"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Seoul",
      /* [] */0
    ],
    /* latlng : tuple */[
      37,
      127.5
    ],
    /* name */"South Korea",
    /* country_code */"KR",
    /* capital */"Seoul"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Belgrade",
      /* [] */0
    ],
    /* latlng : tuple */[
      42.666667,
      21.166667
    ],
    /* name */"Kosovo",
    /* country_code */"XK",
    /* capital */"Pristina"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Kuwait",
      /* [] */0
    ],
    /* latlng : tuple */[
      29.5,
      45.75
    ],
    /* name */"Kuwait",
    /* country_code */"KW",
    /* capital */"Kuwait City"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Vientiane",
      /* [] */0
    ],
    /* latlng : tuple */[
      18,
      105
    ],
    /* name */"Laos",
    /* country_code */"LA",
    /* capital */"Vientiane"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Beirut",
      /* [] */0
    ],
    /* latlng : tuple */[
      33.83333333,
      35.83333333
    ],
    /* name */"Lebanon",
    /* country_code */"LB",
    /* capital */"Beirut"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Monrovia",
      /* [] */0
    ],
    /* latlng : tuple */[
      6.5,
      -9.5
    ],
    /* name */"Liberia",
    /* country_code */"LR",
    /* capital */"Monrovia"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Tripoli",
      /* [] */0
    ],
    /* latlng : tuple */[
      25,
      17
    ],
    /* name */"Libya",
    /* country_code */"LY",
    /* capital */"Tripoli"
  ],
  /* record */[
    /* timezones : :: */[
      "America/St_Lucia",
      /* [] */0
    ],
    /* latlng : tuple */[
      13.88333333,
      -60.96666666
    ],
    /* name */"Saint Lucia",
    /* country_code */"LC",
    /* capital */"Castries"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Vaduz",
      /* [] */0
    ],
    /* latlng : tuple */[
      47.26666666,
      9.53333333
    ],
    /* name */"Liechtenstein",
    /* country_code */"LI",
    /* capital */"Vaduz"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Colombo",
      /* [] */0
    ],
    /* latlng : tuple */[
      7,
      81
    ],
    /* name */"Sri Lanka",
    /* country_code */"LK",
    /* capital */"Colombo"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Maseru",
      /* [] */0
    ],
    /* latlng : tuple */[
      -29.5,
      28.5
    ],
    /* name */"Lesotho",
    /* country_code */"LS",
    /* capital */"Maseru"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Vilnius",
      /* [] */0
    ],
    /* latlng : tuple */[
      56,
      24
    ],
    /* name */"Lithuania",
    /* country_code */"LT",
    /* capital */"Vilnius"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Luxembourg",
      /* [] */0
    ],
    /* latlng : tuple */[
      49.75,
      6.16666666
    ],
    /* name */"Luxembourg",
    /* country_code */"LU",
    /* capital */"Luxembourg"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Riga",
      /* [] */0
    ],
    /* latlng : tuple */[
      57,
      25
    ],
    /* name */"Latvia",
    /* country_code */"LV",
    /* capital */"Riga"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Macau",
      /* [] */0
    ],
    /* latlng : tuple */[
      22.16666666,
      113.55
    ],
    /* name */"Macau",
    /* country_code */"MO",
    /* capital */"Macau"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Marigot",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.08333333,
      -63.95
    ],
    /* name */"Saint Martin",
    /* country_code */"MF",
    /* capital */"Marigot"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Casablanca",
      /* [] */0
    ],
    /* latlng : tuple */[
      32,
      -5
    ],
    /* name */"Morocco",
    /* country_code */"MA",
    /* capital */"Rabat"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Monaco",
      /* [] */0
    ],
    /* latlng : tuple */[
      43.73333333,
      7.4
    ],
    /* name */"Monaco",
    /* country_code */"MC",
    /* capital */"Monaco"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Chisinau",
      /* [] */0
    ],
    /* latlng : tuple */[
      47,
      29
    ],
    /* name */"Moldova",
    /* country_code */"MD",
    /* capital */"Chi\\u0219in\\u0103u"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Antananarivo",
      /* [] */0
    ],
    /* latlng : tuple */[
      -20,
      47
    ],
    /* name */"Madagascar",
    /* country_code */"MG",
    /* capital */"Antananarivo"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Maldives",
      /* [] */0
    ],
    /* latlng : tuple */[
      3.25,
      73
    ],
    /* name */"Maldives",
    /* country_code */"MV",
    /* capital */"Mal\\u00e9"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Mexico_City",
      /* :: */[
        "America/Cancun",
        /* :: */[
          "America/Merida",
          /* :: */[
            "America/Monterrey",
            /* :: */[
              "America/Matamoros",
              /* :: */[
                "America/Mazatlan",
                /* :: */[
                  "America/Chihuahua",
                  /* :: */[
                    "America/Ojinaga",
                    /* :: */[
                      "America/Hermosillo",
                      /* :: */[
                        "America/Tijuana",
                        /* :: */[
                          "America/Bahia_Banderas",
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      23,
      -102
    ],
    /* name */"Mexico",
    /* country_code */"MX",
    /* capital */"Mexico City"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Majuro",
      /* :: */[
        "Pacific/Kwajalein",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      9,
      168
    ],
    /* name */"Marshall Islands",
    /* country_code */"MH",
    /* capital */"Majuro"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Skopje",
      /* [] */0
    ],
    /* latlng : tuple */[
      41.83333333,
      22
    ],
    /* name */"Macedonia",
    /* country_code */"MK",
    /* capital */"Skopje"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Bamako",
      /* [] */0
    ],
    /* latlng : tuple */[
      17,
      -4
    ],
    /* name */"Mali",
    /* country_code */"ML",
    /* capital */"Bamako"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Malta",
      /* [] */0
    ],
    /* latlng : tuple */[
      35.83333333,
      14.58333333
    ],
    /* name */"Malta",
    /* country_code */"MT",
    /* capital */"Valletta"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Rangoon",
      /* [] */0
    ],
    /* latlng : tuple */[
      22,
      98
    ],
    /* name */"Myanmar",
    /* country_code */"MM",
    /* capital */"Naypyidaw"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Podgorica",
      /* [] */0
    ],
    /* latlng : tuple */[
      42.5,
      19.3
    ],
    /* name */"Montenegro",
    /* country_code */"ME",
    /* capital */"Podgorica"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Ulaanbaatar",
      /* :: */[
        "Asia/Hovd",
        /* :: */[
          "Asia/Choibalsan",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      46,
      105
    ],
    /* name */"Mongolia",
    /* country_code */"MN",
    /* capital */"Ulan Bator"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Saipan",
      /* [] */0
    ],
    /* latlng : tuple */[
      15.2,
      145.75
    ],
    /* name */"Northern Mariana Islands",
    /* country_code */"MP",
    /* capital */"Saipan"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Maputo",
      /* [] */0
    ],
    /* latlng : tuple */[
      -18.25,
      35
    ],
    /* name */"Mozambique",
    /* country_code */"MZ",
    /* capital */"Maputo"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Nouakchott",
      /* [] */0
    ],
    /* latlng : tuple */[
      20,
      -12
    ],
    /* name */"Mauritania",
    /* country_code */"MR",
    /* capital */"Nouakchott"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Montserrat",
      /* [] */0
    ],
    /* latlng : tuple */[
      16.75,
      -62.2
    ],
    /* name */"Montserrat",
    /* country_code */"MS",
    /* capital */"Plymouth"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Martinique",
      /* [] */0
    ],
    /* latlng : tuple */[
      14.666667,
      -61
    ],
    /* name */"Martinique",
    /* country_code */"MQ",
    /* capital */"Fort-de-France"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Mauritius",
      /* [] */0
    ],
    /* latlng : tuple */[
      -20.28333333,
      57.55
    ],
    /* name */"Mauritius",
    /* country_code */"MU",
    /* capital */"Port Louis"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Blantyre",
      /* [] */0
    ],
    /* latlng : tuple */[
      -13.5,
      34
    ],
    /* name */"Malawi",
    /* country_code */"MW",
    /* capital */"Lilongwe"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Kuala_Lumpur",
      /* :: */[
        "Asia/Kuching",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      2.5,
      112.5
    ],
    /* name */"Malaysia",
    /* country_code */"MY",
    /* capital */"Kuala Lumpur"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Mayotte",
      /* [] */0
    ],
    /* latlng : tuple */[
      -12.83333333,
      45.16666666
    ],
    /* name */"Mayotte",
    /* country_code */"YT",
    /* capital */"Mamoudzou"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Windhoek",
      /* [] */0
    ],
    /* latlng : tuple */[
      -22,
      17
    ],
    /* name */"Namibia",
    /* country_code */"NA",
    /* capital */"Windhoek"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Noumea",
      /* [] */0
    ],
    /* latlng : tuple */[
      -21.5,
      165.5
    ],
    /* name */"New Caledonia",
    /* country_code */"NC",
    /* capital */"Noum\\u00e9a"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Niamey",
      /* [] */0
    ],
    /* latlng : tuple */[
      16,
      8
    ],
    /* name */"Niger",
    /* country_code */"NE",
    /* capital */"Niamey"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Norfolk",
      /* [] */0
    ],
    /* latlng : tuple */[
      -29.03333333,
      167.95
    ],
    /* name */"Norfolk Island",
    /* country_code */"NF",
    /* capital */"Kingston"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Lagos",
      /* [] */0
    ],
    /* latlng : tuple */[
      10,
      8
    ],
    /* name */"Nigeria",
    /* country_code */"NG",
    /* capital */"Abuja"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Managua",
      /* [] */0
    ],
    /* latlng : tuple */[
      13,
      -85
    ],
    /* name */"Nicaragua",
    /* country_code */"NI",
    /* capital */"Managua"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Niue",
      /* [] */0
    ],
    /* latlng : tuple */[
      -19.03333333,
      -169.86666666
    ],
    /* name */"Niue",
    /* country_code */"NU",
    /* capital */"Alofi"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Amsterdam",
      /* [] */0
    ],
    /* latlng : tuple */[
      52.5,
      5.75
    ],
    /* name */"Netherlands",
    /* country_code */"NL",
    /* capital */"Amsterdam"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Oslo",
      /* [] */0
    ],
    /* latlng : tuple */[
      62,
      10
    ],
    /* name */"Norway",
    /* country_code */"NO",
    /* capital */"Oslo"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Kathmandu",
      /* [] */0
    ],
    /* latlng : tuple */[
      28,
      84
    ],
    /* name */"Nepal",
    /* country_code */"NP",
    /* capital */"Kathmandu"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Nauru",
      /* [] */0
    ],
    /* latlng : tuple */[
      -0.53333333,
      166.91666666
    ],
    /* name */"Nauru",
    /* country_code */"NR",
    /* capital */"Yaren"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Auckland",
      /* :: */[
        "Pacific/Chatham",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      -41,
      174
    ],
    /* name */"New Zealand",
    /* country_code */"NZ",
    /* capital */"Wellington"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Muscat",
      /* [] */0
    ],
    /* latlng : tuple */[
      21,
      57
    ],
    /* name */"Oman",
    /* country_code */"OM",
    /* capital */"Muscat"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Karachi",
      /* [] */0
    ],
    /* latlng : tuple */[
      30,
      70
    ],
    /* name */"Pakistan",
    /* country_code */"PK",
    /* capital */"Islamabad"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Panama",
      /* [] */0
    ],
    /* latlng : tuple */[
      9,
      -80
    ],
    /* name */"Panama",
    /* country_code */"PA",
    /* capital */"Panama City"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Pitcairn",
      /* [] */0
    ],
    /* latlng : tuple */[
      -25.06666666,
      -130.1
    ],
    /* name */"Pitcairn Islands",
    /* country_code */"PN",
    /* capital */"Adamstown"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Lima",
      /* [] */0
    ],
    /* latlng : tuple */[
      -10,
      -76
    ],
    /* name */"Peru",
    /* country_code */"PE",
    /* capital */"Lima"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Manila",
      /* [] */0
    ],
    /* latlng : tuple */[
      13,
      122
    ],
    /* name */"Philippines",
    /* country_code */"PH",
    /* capital */"Manila"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Palau",
      /* [] */0
    ],
    /* latlng : tuple */[
      7.5,
      134.5
    ],
    /* name */"Palau",
    /* country_code */"PW",
    /* capital */"Ngerulmud"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Port_Moresby",
      /* :: */[
        "Pacific/Bougainville",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      -6,
      147
    ],
    /* name */"Papua New Guinea",
    /* country_code */"PG",
    /* capital */"Port Moresby"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Warsaw",
      /* [] */0
    ],
    /* latlng : tuple */[
      52,
      20
    ],
    /* name */"Poland",
    /* country_code */"PL",
    /* capital */"Warsaw"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Puerto_Rico",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.25,
      -66.5
    ],
    /* name */"Puerto Rico",
    /* country_code */"PR",
    /* capital */"San Juan"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Pyongyang",
      /* [] */0
    ],
    /* latlng : tuple */[
      40,
      127
    ],
    /* name */"North Korea",
    /* country_code */"KP",
    /* capital */"Pyongyang"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Lisbon",
      /* :: */[
        "Atlantic/Madeira",
        /* :: */[
          "Atlantic/Azores",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      39.5,
      -8
    ],
    /* name */"Portugal",
    /* country_code */"PT",
    /* capital */"Lisbon"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Asuncion",
      /* [] */0
    ],
    /* latlng : tuple */[
      -23,
      -58
    ],
    /* name */"Paraguay",
    /* country_code */"PY",
    /* capital */"Asunci\\u00f3n"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Gaza",
      /* :: */[
        "Asia/Hebron",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      31.9,
      35.2
    ],
    /* name */"Palestine",
    /* country_code */"PS",
    /* capital */"Ramallah"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Tahiti",
      /* :: */[
        "Pacific/Marquesas",
        /* :: */[
          "Pacific/Gambier",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      -15,
      -140
    ],
    /* name */"French Polynesia",
    /* country_code */"PF",
    /* capital */"Papeet\\u0113"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Qatar",
      /* [] */0
    ],
    /* latlng : tuple */[
      25.5,
      51.25
    ],
    /* name */"Qatar",
    /* country_code */"QA",
    /* capital */"Doha"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Reunion",
      /* [] */0
    ],
    /* latlng : tuple */[
      -21.15,
      55.5
    ],
    /* name */"R\\u00e9union",
    /* country_code */"RE",
    /* capital */"Saint-Denis"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Bucharest",
      /* [] */0
    ],
    /* latlng : tuple */[
      46,
      25
    ],
    /* name */"Romania",
    /* country_code */"RO",
    /* capital */"Bucharest"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Kaliningrad",
      /* :: */[
        "Europe/Moscow",
        /* :: */[
          "Europe/Simferopol",
          /* :: */[
            "Europe/Volgograd",
            /* :: */[
              "Europe/Kirov",
              /* :: */[
                "Europe/Astrakhan",
                /* :: */[
                  "Europe/Samara",
                  /* :: */[
                    "Europe/Ulyanovsk",
                    /* :: */[
                      "Asia/Yekaterinburg",
                      /* :: */[
                        "Asia/Omsk",
                        /* :: */[
                          "Asia/Novosibirsk",
                          /* :: */[
                            "Asia/Barnaul",
                            /* :: */[
                              "Asia/Tomsk",
                              /* :: */[
                                "Asia/Novokuznetsk",
                                /* :: */[
                                  "Asia/Krasnoyarsk",
                                  /* :: */[
                                    "Asia/Irkutsk",
                                    /* :: */[
                                      "Asia/Chita",
                                      /* :: */[
                                        "Asia/Yakutsk",
                                        /* :: */[
                                          "Asia/Khandyga",
                                          /* :: */[
                                            "Asia/Vladivostok",
                                            /* :: */[
                                              "Asia/Ust-Nera",
                                              /* :: */[
                                                "Asia/Magadan",
                                                /* :: */[
                                                  "Asia/Sakhalin",
                                                  /* :: */[
                                                    "Asia/Srednekolymsk",
                                                    /* :: */[
                                                      "Asia/Kamchatka",
                                                      /* :: */[
                                                        "Asia/Anadyr",
                                                        /* [] */0
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      60,
      100
    ],
    /* name */"Russia",
    /* country_code */"RU",
    /* capital */"Moscow"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Kigali",
      /* [] */0
    ],
    /* latlng : tuple */[
      -2,
      30
    ],
    /* name */"Rwanda",
    /* country_code */"RW",
    /* capital */"Kigali"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Riyadh",
      /* [] */0
    ],
    /* latlng : tuple */[
      25,
      45
    ],
    /* name */"Saudi Arabia",
    /* country_code */"SA",
    /* capital */"Riyadh"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Khartoum",
      /* [] */0
    ],
    /* latlng : tuple */[
      15,
      30
    ],
    /* name */"Sudan",
    /* country_code */"SD",
    /* capital */"Khartoum"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Dakar",
      /* [] */0
    ],
    /* latlng : tuple */[
      14,
      -14
    ],
    /* name */"Senegal",
    /* country_code */"SN",
    /* capital */"Dakar"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Singapore",
      /* [] */0
    ],
    /* latlng : tuple */[
      1.36666666,
      103.8
    ],
    /* name */"Singapore",
    /* country_code */"SG",
    /* capital */"Singapore"
  ],
  /* record */[
    /* timezones : :: */[
      "Atlantic/South_Georgia",
      /* [] */0
    ],
    /* latlng : tuple */[
      -54.5,
      -37
    ],
    /* name */"South Georgia",
    /* country_code */"GS",
    /* capital */"King Edward Point"
  ],
  /* record */[
    /* timezones : :: */[
      "Arctic/Longyearbyen",
      /* [] */0
    ],
    /* latlng : tuple */[
      78,
      20
    ],
    /* name */"Svalbard and Jan Mayen",
    /* country_code */"SJ",
    /* capital */"Longyearbyen"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Guadalcanal",
      /* [] */0
    ],
    /* latlng : tuple */[
      -8,
      159
    ],
    /* name */"Solomon Islands",
    /* country_code */"SB",
    /* capital */"Honiara"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Freetown",
      /* [] */0
    ],
    /* latlng : tuple */[
      8.5,
      -11.5
    ],
    /* name */"Sierra Leone",
    /* country_code */"SL",
    /* capital */"Freetown"
  ],
  /* record */[
    /* timezones : :: */[
      "America/El_Salvador",
      /* [] */0
    ],
    /* latlng : tuple */[
      13.83333333,
      -88.91666666
    ],
    /* name */"El Salvador",
    /* country_code */"SV",
    /* capital */"San Salvador"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/San_Marino",
      /* [] */0
    ],
    /* latlng : tuple */[
      43.76666666,
      12.41666666
    ],
    /* name */"San Marino",
    /* country_code */"SM",
    /* capital */"City of San Marino"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Mogadishu",
      /* [] */0
    ],
    /* latlng : tuple */[
      10,
      49
    ],
    /* name */"Somalia",
    /* country_code */"SO",
    /* capital */"Mogadishu"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Miquelon",
      /* [] */0
    ],
    /* latlng : tuple */[
      46.83333333,
      -56.33333333
    ],
    /* name */"Saint Pierre and Miquelon",
    /* country_code */"PM",
    /* capital */"Saint-Pierre"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Belgrade",
      /* [] */0
    ],
    /* latlng : tuple */[
      44,
      21
    ],
    /* name */"Serbia",
    /* country_code */"RS",
    /* capital */"Belgrade"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Juba",
      /* [] */0
    ],
    /* latlng : tuple */[
      7,
      30
    ],
    /* name */"South Sudan",
    /* country_code */"SS",
    /* capital */"Juba"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Sao_Tome",
      /* [] */0
    ],
    /* latlng : tuple */[
      1,
      7
    ],
    /* name */"S\\u00e3o Tom\\u00e9 and Pr\\u00edncipe",
    /* country_code */"ST",
    /* capital */"S\\u00e3o Tom\\u00e9"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Paramaribo",
      /* [] */0
    ],
    /* latlng : tuple */[
      4,
      -56
    ],
    /* name */"Suriname",
    /* country_code */"SR",
    /* capital */"Paramaribo"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Bratislava",
      /* [] */0
    ],
    /* latlng : tuple */[
      48.66666666,
      19.5
    ],
    /* name */"Slovakia",
    /* country_code */"SK",
    /* capital */"Bratislava"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Ljubljana",
      /* [] */0
    ],
    /* latlng : tuple */[
      46.11666666,
      14.81666666
    ],
    /* name */"Slovenia",
    /* country_code */"SI",
    /* capital */"Ljubljana"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Stockholm",
      /* [] */0
    ],
    /* latlng : tuple */[
      62,
      15
    ],
    /* name */"Sweden",
    /* country_code */"SE",
    /* capital */"Stockholm"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Mbabane",
      /* [] */0
    ],
    /* latlng : tuple */[
      -26.5,
      31.5
    ],
    /* name */"Swaziland",
    /* country_code */"SZ",
    /* capital */"Lobamba"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Lower_Princes",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.033333,
      -63.05
    ],
    /* name */"Sint Maarten",
    /* country_code */"SX",
    /* capital */"Philipsburg"
  ],
  /* record */[
    /* timezones : :: */[
      "Indian/Mahe",
      /* [] */0
    ],
    /* latlng : tuple */[
      -4.58333333,
      55.66666666
    ],
    /* name */"Seychelles",
    /* country_code */"SC",
    /* capital */"Victoria"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Damascus",
      /* [] */0
    ],
    /* latlng : tuple */[
      35,
      38
    ],
    /* name */"Syria",
    /* country_code */"SY",
    /* capital */"Damascus"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Grand_Turk",
      /* [] */0
    ],
    /* latlng : tuple */[
      21.75,
      -71.58333333
    ],
    /* name */"Turks and Caicos Islands",
    /* country_code */"TC",
    /* capital */"Cockburn Town"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Ndjamena",
      /* [] */0
    ],
    /* latlng : tuple */[
      15,
      19
    ],
    /* name */"Chad",
    /* country_code */"TD",
    /* capital */"N'Djamena"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Lome",
      /* [] */0
    ],
    /* latlng : tuple */[
      8,
      1.16666666
    ],
    /* name */"Togo",
    /* country_code */"TG",
    /* capital */"Lom\\u00e9"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Bangkok",
      /* [] */0
    ],
    /* latlng : tuple */[
      15,
      100
    ],
    /* name */"Thailand",
    /* country_code */"TH",
    /* capital */"Bangkok"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Dushanbe",
      /* [] */0
    ],
    /* latlng : tuple */[
      39,
      71
    ],
    /* name */"Tajikistan",
    /* country_code */"TJ",
    /* capital */"Dushanbe"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Fakaofo",
      /* [] */0
    ],
    /* latlng : tuple */[
      -9,
      -172
    ],
    /* name */"Tokelau",
    /* country_code */"TK",
    /* capital */"Fakaofo"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Ashgabat",
      /* [] */0
    ],
    /* latlng : tuple */[
      40,
      60
    ],
    /* name */"Turkmenistan",
    /* country_code */"TM",
    /* capital */"Ashgabat"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Dili",
      /* [] */0
    ],
    /* latlng : tuple */[
      -8.83333333,
      125.91666666
    ],
    /* name */"Timor-Leste",
    /* country_code */"TL",
    /* capital */"Dili"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Tongatapu",
      /* [] */0
    ],
    /* latlng : tuple */[
      -20,
      -175
    ],
    /* name */"Tonga",
    /* country_code */"TO",
    /* capital */"Nuku'alofa"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Port_of_Spain",
      /* [] */0
    ],
    /* latlng : tuple */[
      11,
      -61
    ],
    /* name */"Trinidad and Tobago",
    /* country_code */"TT",
    /* capital */"Port of Spain"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Tunis",
      /* [] */0
    ],
    /* latlng : tuple */[
      34,
      9
    ],
    /* name */"Tunisia",
    /* country_code */"TN",
    /* capital */"Tunis"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Istanbul",
      /* [] */0
    ],
    /* latlng : tuple */[
      39,
      35
    ],
    /* name */"Turkey",
    /* country_code */"TR",
    /* capital */"Ankara"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Funafuti",
      /* [] */0
    ],
    /* latlng : tuple */[
      -8,
      178
    ],
    /* name */"Tuvalu",
    /* country_code */"TV",
    /* capital */"Funafuti"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Taipei",
      /* [] */0
    ],
    /* latlng : tuple */[
      23.5,
      121
    ],
    /* name */"Taiwan",
    /* country_code */"TW",
    /* capital */"Taipei"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Dar_es_Salaam",
      /* [] */0
    ],
    /* latlng : tuple */[
      -6,
      35
    ],
    /* name */"Tanzania",
    /* country_code */"TZ",
    /* capital */"Dodoma"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Kampala",
      /* [] */0
    ],
    /* latlng : tuple */[
      1,
      32
    ],
    /* name */"Uganda",
    /* country_code */"UG",
    /* capital */"Kampala"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Kiev",
      /* :: */[
        "Europe/Uzhgorod",
        /* :: */[
          "Europe/Zaporozhye",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      49,
      32
    ],
    /* name */"Ukraine",
    /* country_code */"UA",
    /* capital */"Kiev"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Johnston",
      /* :: */[
        "Pacific/Midway",
        /* :: */[
          "Pacific/Wake",
          /* [] */0
        ]
      ]
    ],
    /* latlng : tuple */[
      19.2911437,
      166.618332
    ],
    /* name */"United States Minor Outlying Islands",
    /* country_code */"UM",
    /* capital */"United States Minor Outlying Islands"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Montevideo",
      /* [] */0
    ],
    /* latlng : tuple */[
      -33,
      -56
    ],
    /* name */"Uruguay",
    /* country_code */"UY",
    /* capital */"Montevideo"
  ],
  /* record */[
    /* timezones : :: */[
      "America/New_York",
      /* :: */[
        "America/Detroit",
        /* :: */[
          "America/Kentucky/Louisville",
          /* :: */[
            "America/Kentucky/Monticello",
            /* :: */[
              "America/Indiana/Indianapolis",
              /* :: */[
                "America/Indiana/Vincennes",
                /* :: */[
                  "America/Indiana/Winamac",
                  /* :: */[
                    "America/Indiana/Marengo",
                    /* :: */[
                      "America/Indiana/Petersburg",
                      /* :: */[
                        "America/Indiana/Vevay",
                        /* :: */[
                          "America/Chicago",
                          /* :: */[
                            "America/Indiana/Tell_City",
                            /* :: */[
                              "America/Indiana/Knox",
                              /* :: */[
                                "America/Menominee",
                                /* :: */[
                                  "America/North_Dakota/Center",
                                  /* :: */[
                                    "America/North_Dakota/New_Salem",
                                    /* :: */[
                                      "America/North_Dakota/Beulah",
                                      /* :: */[
                                        "America/Denver",
                                        /* :: */[
                                          "America/Boise",
                                          /* :: */[
                                            "America/Phoenix",
                                            /* :: */[
                                              "America/Los_Angeles",
                                              /* :: */[
                                                "America/Anchorage",
                                                /* :: */[
                                                  "America/Juneau",
                                                  /* :: */[
                                                    "America/Sitka",
                                                    /* :: */[
                                                      "America/Metlakatla",
                                                      /* :: */[
                                                        "America/Yakutat",
                                                        /* :: */[
                                                          "America/Nome",
                                                          /* :: */[
                                                            "America/Adak",
                                                            /* :: */[
                                                              "Pacific/Honolulu",
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ],
    /* latlng : tuple */[
      38,
      -97
    ],
    /* name */"United States",
    /* country_code */"US",
    /* capital */"Washington D.C."
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Samarkand",
      /* :: */[
        "Asia/Tashkent",
        /* [] */0
      ]
    ],
    /* latlng : tuple */[
      41,
      64
    ],
    /* name */"Uzbekistan",
    /* country_code */"UZ",
    /* capital */"Tashkent"
  ],
  /* record */[
    /* timezones : :: */[
      "Europe/Vatican",
      /* [] */0
    ],
    /* latlng : tuple */[
      41.9,
      12.45
    ],
    /* name */"Vatican City",
    /* country_code */"VA",
    /* capital */"Vatican City"
  ],
  /* record */[
    /* timezones : :: */[
      "America/St_Vincent",
      /* [] */0
    ],
    /* latlng : tuple */[
      13.25,
      -61.2
    ],
    /* name */"Saint Vincent and the Grenadines",
    /* country_code */"VC",
    /* capital */"Kingstown"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Caracas",
      /* [] */0
    ],
    /* latlng : tuple */[
      8,
      -66
    ],
    /* name */"Venezuela",
    /* country_code */"VE",
    /* capital */"Caracas"
  ],
  /* record */[
    /* timezones : :: */[
      "America/Tortola",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.431383,
      -64.62305
    ],
    /* name */"British Virgin Islands",
    /* country_code */"VG",
    /* capital */"Road Town"
  ],
  /* record */[
    /* timezones : :: */[
      "America/St_Thomas",
      /* [] */0
    ],
    /* latlng : tuple */[
      18.35,
      -64.933333
    ],
    /* name */"United States Virgin Islands",
    /* country_code */"VI",
    /* capital */"Charlotte Amalie"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Ho_Chi_Minh",
      /* [] */0
    ],
    /* latlng : tuple */[
      16.16666666,
      107.83333333
    ],
    /* name */"Vietnam",
    /* country_code */"VN",
    /* capital */"Hanoi"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Efate",
      /* [] */0
    ],
    /* latlng : tuple */[
      -16,
      167
    ],
    /* name */"Vanuatu",
    /* country_code */"VU",
    /* capital */"Port Vila"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Wallis",
      /* [] */0
    ],
    /* latlng : tuple */[
      -13.3,
      -176.2
    ],
    /* name */"Wallis and Futuna",
    /* country_code */"WF",
    /* capital */"Mata-Utu"
  ],
  /* record */[
    /* timezones : :: */[
      "Pacific/Apia",
      /* [] */0
    ],
    /* latlng : tuple */[
      -13.58333333,
      -172.33333333
    ],
    /* name */"Samoa",
    /* country_code */"WS",
    /* capital */"Apia"
  ],
  /* record */[
    /* timezones : :: */[
      "Asia/Aden",
      /* [] */0
    ],
    /* latlng : tuple */[
      15,
      48
    ],
    /* name */"Yemen",
    /* country_code */"YE",
    /* capital */"Sana'a"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Johannesburg",
      /* [] */0
    ],
    /* latlng : tuple */[
      -29,
      24
    ],
    /* name */"South Africa",
    /* country_code */"ZA",
    /* capital */"Pretoria"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Lusaka",
      /* [] */0
    ],
    /* latlng : tuple */[
      -15,
      30
    ],
    /* name */"Zambia",
    /* country_code */"ZM",
    /* capital */"Lusaka"
  ],
  /* record */[
    /* timezones : :: */[
      "Africa/Harare",
      /* [] */0
    ],
    /* latlng : tuple */[
      -20,
      30
    ],
    /* name */"Zimbabwe",
    /* country_code */"ZW",
    /* capital */"Harare"
  ]
];

function getByCode(name) {
  var exit = 0;
  var item;
  try {
    item = List.find((function (i) {
            return i[/* name */2] === name;
          }), $$Array.to_list(countries));
    exit = 1;
  }
  catch (exn){
    if (exn === Caml_builtin_exceptions.not_found) {
      return undefined;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    return item;
  }
  
}

exports.countries = countries;
exports.getByCode = getByCode;
/* No side effect */
