// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function ListItem(Props) {
  var name = Props.name;
  var onAddCountry = Props.onAddCountry;
  var match = Props.color;
  var color = match !== undefined ? match : "#becce2";
  return React.createElement("li", {
              key: name,
              style: {
                backgroundColor: color,
                border: "1px solid black",
                cursor: "pointer",
                height: "30px",
                lineHeight: "30px",
                margin: "10px 0",
                textAlign: "center",
                borderRadius: "5px",
                userSelect: "none"
              },
              onClick: (function (_e) {
                  return Curry._1(onAddCountry, name);
                })
            }, React.createElement("div", undefined, name));
}

var make = ListItem;

exports.make = make;
/* react Not a pure module */
