// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var Data$ReactHooksTemplate = require("./utils/Data.bs.js");
var ListItem$ReactHooksTemplate = require("./utils/ListItem.bs.js");

function CountryList__f(Props) {
  var onAddCountry = Props.onAddCountry;
  var selected = Props.selected;
  return React.createElement("ul", {
              style: {
                listStyle: "none",
                margin: "0",
                padding: "0"
              }
            }, $$Array.map((function (c) {
                    return React.createElement(ListItem$ReactHooksTemplate.make, {
                                name: c[/* name */2],
                                onAddCountry: onAddCountry,
                                key: c[/* name */2]
                              });
                  }), $$Array.of_list(List.filter((function (country) {
                              try {
                                List.find((function (selected) {
                                        return selected === country[/* name */2];
                                      }), selected);
                                return false;
                              }
                              catch (exn){
                                if (exn === Caml_builtin_exceptions.not_found) {
                                  return true;
                                } else {
                                  throw exn;
                                }
                              }
                            }))($$Array.to_list(Data$ReactHooksTemplate.countries)))));
}

var make = CountryList__f;

exports.make = make;
/* react Not a pure module */
