// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Utils$ReactHooksTemplate = require("./utils/Utils.bs.js");
var Client$ReactHooksTemplate = require("./utils/Client.bs.js");
var FixForReasonApolloJsxV3$ReactHooksTemplate = require("./utils/FixForReasonApolloJsxV3.bs.js");

var component = ReasonReact.statelessComponent("IndexFixForReasonApolloJsxV3");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, ApolloProvider.make(Client$ReactHooksTemplate.instance, /* array */[ReasonReact.element(undefined, undefined, FixForReasonApolloJsxV3$ReactHooksTemplate.make(Utils$ReactHooksTemplate.demoVersion, /* array */[]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Main = /* module */[
  /* component */component,
  /* make */make
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, make(/* array */[])), "root");

exports.Main = Main;
/* component Not a pure module */
